version: '3.3'
services:
  jupyter:
    build: ./docker
    container_name: learning-for-ml_notebook
    volumes:
      - ./notebook:/workspace
      - ./datasets:/workspace/datasets
    ports:
      - 1016:8000
    env_file:
      - ./.env
